[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "epygram"
version = "1.4.21"
description = "Bah C'est EPyGrAM quoi d'autre !!!"
authors = [
    { name = "Alexandre MARY", email = "a.mary@meteo.fr" },
    { name = "Suzat ** "  , email = "f.suzat@meteo.fr"}
]
maintainers = [
  {name = "Walid CHIKHI", email = "waliidchikhi@gmail.com" }
]


readme = "README.md"
license = {file = "LICENSE.txt"}


requires-python = ">=3.9"
dependencies=[
"taylorism",
"footprints",
"bronx",
"numpy",
"cartopy == 0.23.0",
"matplotlib == 3.8.4",
"eccodes",
"vtk",
"vortex",
"pillow",
"contourpy",
"h5py",
"netCDF4",
"pyproj",
"pyresample",
"scipy",
"six",
"web.py",
]

[project.urls]
documentation = "https://github.com/UMR-CNRM/EPyGrAM-doc.git"
source = "https://github.com/UMR-CNRM/EPyGrAM.git"
download = "https://github.com/UMR-CNRM/EPyGrAM/releases"
tracker = "https://github.com/UMR-CNRM/EPyGrAM/issues"


[tool.setuptools]
include-package-data = true


[tool.setuptools.packages.find]
where = ["src"]
