[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "epygram"
version = "1.5.0"
description = "EPyGrAM : Enhanced Python for Graphics and Analysis of Meteorological fields"
authors = [
    { name = "Alexandre MARY", email = "alexandre.mary@meteo.fr" },
    { name = "Sébastien Riette"  , email = "sebastien.riette@meteo.fr"}
]
maintainers = [
  { name = "Alexandre MARY", email = "alexandre.mary@meteo.fr" }, 
  { name = "Sébastien Riette"  , email = "sebastien.riette@meteo.fr"}
  { name = "Walid CHIKHI", email = "waliidchikhi@gmail.com" }
]

readme = "README.md"
license = {file = "LICENSE.txt"}

classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Developers',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Operating System :: Unix',
]


requires-python = ">=3.6"
dependencies=[
        "footprints",
        "bronx",
        "numpy",
        "cartopy == 0.23.0",   
        "matplotlib == 3.8.4",
        "eccodes",      
        "netCDF4",   
        "pyproj",      
        "six",
	"pyyaml" , # issue with bronx !!          
            ]
[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
docs = [
    "sphinx",
       ]
graphics = [
        "vtk",
        "contourpy",
        ]
features=[
  "taylorism",
  "pyresample",
  "scipy",
  "web.py"
    ]
format=[
  "h5py",
  "pillow"
  ]

vortex = [
  "vortex"
      ]
all = [
        "taylorism",  
        "footprints",
        "bronx",
        "numpy",
        "cartopy == 0.23.0",   
        "matplotlib == 3.8.4",
        "eccodes",      
        "vtk",   
        "vortex",  
        "pillow",  
        "contourpy",    
        "h5py",     
        "netCDF4",   
        "pyproj",      
        "pyresample",    
        "scipy", 
        "six",         
        "web.py"
         ]

[project.urls]
documentation = "https://umr-cnrm.github.io/EPyGrAM-doc"
source = "https://github.com/UMR-CNRM/EPyGrAM.git"
download = "https://github.com/UMR-CNRM/EPyGrAM/releases"
tracker = "https://github.com/UMR-CNRM/EPyGrAM/issues"

[tool.pytest.ini_options]
pythonpath = [
    "src",
             ]

testpaths = [
    "tests"
            ]
